// This is a webpack plugin to expose the data generated by SriPlugin.
// See webpack.prod.config.babel.js
import fs from 'fs';

import { oneLine } from 'common-tags';

// TODO: hopefully we can uplift this.
// See https://github.com/waysact/webpack-subresource-integrity/issues/45

export default class SriDataPlugin {
  constructor({ saveAs } = {}) {
    if (!saveAs) {
      throw new Error('The saveAs parameter cannot be empty');
    }
    this.saveAs = saveAs;
  }

  apply(compiler) {
    compiler.plugin('done', (stats) => {
      const sriStats = {};
      try {
        Object.values(stats.toJson().assetsByChunkName).forEach(
          (chunkFileResult) => {
            const chunkFiles = Array.isArray(chunkFileResult) ?
              chunkFileResult : [chunkFileResult];
            chunkFiles.forEach((baseName) => {
              const asset = stats.compilation.assets[baseName];
              if (!asset.integrity) {
                throw new Error(
                  oneLine`The integrity property is falsey for
                  asset ${baseName}; Is the webpack-subresource-integrity
                  plugin installed and enabled?`);
              }
              sriStats[baseName] = asset.integrity;
            });
          }
        );

        fs.writeFileSync(this.saveAs, JSON.stringify(sriStats));
      } catch (error) {
        stats.compilation.errors.push(error);
      }
    });
  }
}
