import fs from 'fs';

import { oneLine } from 'common-tags';
import config from 'config';

// This is a webpack plugin to expose the data generated by SriPlugin.
// See webpack.prod.config.babel.js
export default class SriDataPlugin {
  constructor({ saveAs, _config = config } = {}) {
    this.config = _config;

    if (!saveAs) {
      throw new Error('The saveAs parameter cannot be empty');
    }
    this.saveAs = saveAs;
  }

  apply(compiler) {
    const loadableStatsFilename = this.config.get('loadableStatsFilename');

    compiler.plugin('done', (stats) => {
      const sriStats = {};
      try {
        Object.keys(stats.compilation.assets).forEach((baseName) => {
          const asset = stats.compilation.assets[baseName];
          // The `loadable-stats.json` is created by the `LoadablePlugin`
          // (webpack). No need to create SRI for it, it is only used by the
          // server.
          if (baseName !== loadableStatsFilename && !asset.integrity) {
            throw new Error(
              oneLine`The integrity property is falsey for
              asset ${baseName}; Is the webpack-subresource-integrity
              plugin installed and enabled?`,
            );
          }
          sriStats[baseName] = asset.integrity;
        });

        fs.writeFileSync(this.saveAs, JSON.stringify(sriStats));
      } catch (error) {
        stats.compilation.errors.push(error);
      }
    });
  }
}
