#
# Build
#
FROM node:16-slim AS builder

WORKDIR /srv/node
COPY package.json yarn.lock /srv/node/

RUN yarn install --pure-lockfile

#
# Install
#
FROM node:16-slim

ARG olympia_uid=9500

RUN useradd -u ${olympia_uid} -d /home/olympia -m -s /sbin/nologin olympia

USER ${olympia_uid}:${olympia_uid}

# The V2 Pipeline expects version.json to be located in /app/
# As a temporary measure symlink to the version.json generated by Circle-CI
WORKDIR /app
RUN ln -s /srv/code/version.json /app/version.json

WORKDIR /srv/code

COPY --chown=${olympia_uid}:${olympia_uid} . /srv/code/

# Replace the local node_modules with the ones we installed above.
RUN rm -rf node_modules
COPY --from=builder --chown=${olympia_uid}:${olympia_uid} /srv/node/node_modules /srv/code/node_modules

ENV SERVER_HOST 0.0.0.0
ENV SERVER_PORT 4000

CMD yarn start
